![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
# Importamos numpy
import numpy as np
np.__version__

'2.2.5'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [48]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [6]:
# Matriz con 100es
verdadero = np.full((3,3), True) # dos entradas, shape y lo que quiero que me ponga
verdadero

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [51]:
"""
impares = []
for num in my_array:
    if num % 2 != 0:
        impares.append(num)
"""

mask = my_array%2 != 0

my_array[mask]

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [57]:
"""
for i in range(len(my_array)):
    if my_array[i] % 2 != 0:
        my_array[i] = -1
"""
mask = my_array%2 != 0

my_array[mask] = -1
print(my_array)         #verlo pq me pide en una variable nueva y me da uno

[ 0 -1  2 -1  4 -1  6 -1  8 -1]



## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [58]:
np.where(my_array%2!=0, -1, my_array)  # condicion, si si hace esto, si no hace esto

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [60]:
my_array.reshape(2,5) # (filas, columnas) y lo de dos dimensiones es lo de ver las llaves

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [61]:
a = np.arange(10).reshape(2,-1)  
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a,b]) # la segunda coma podría aclarar un axis=1 es vertical y axis=0

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [26]:
(a + b) #creo q está mal

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [63]:
print(np.concatenate.__doc__)


    concatenate(
        (a1, a2, ...),
        axis=0,
        out=None,
        dtype=None,
        casting="same_kind"
    )

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [ ]:
my_array = np.arange(10)
my_array = [my_array * 10]
my_array[0]
my_array[-1]
my_array[1:8]

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [69]:
my_matrix = np.random.rand(3,3)
print(my_matrix)

[[0.01086823 0.11892133 0.31031476]
 [0.07524854 0.75979404 0.02121251]
 [0.60170828 0.4972377  0.86491413]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [70]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [ ]:
# comando para dar vuelta algo [::-1]

In [72]:
secuencia = np.arange(4,1,-0.25)
print(secuencia)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

In [78]:
! pip install matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 25.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 41.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 38.3 MB/s eta 0:00:00


![imagen](./img/numpy.png)

In [79]:
import matplotlib.pyplot as plt

imagen = plt.imread("./img/numpy.png")
print(type(imagen))
print(imagen.shape)

plt.imshow(imagen)

Matplotlib is building the font cache; this may take a moment.


<class 'numpy.ndarray'>
(306, 765, 4)


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [75]:
np.ones((4,1)).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [ ]:
np.random.rand(4,5,3) #4 matrices de 5x3

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [ ]:
np.array([False]*10).reshape(2,5)

In [76]:
np.full((10,1),False).reshape(2,5)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [ ]:
# 3 elementos
# 